apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
type: Opaque
data:
  mysql-user: {{ .Values.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
