pipeline {
    agent any
    environment {
        MAVEN_HOME = tool 'Maven-3.9.0' 
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Utsav0701/pipeline-task-day12.git', branch: 'main', credentialsId: 'gitcard'
            }
        }

        stage('Build') {
            steps {
                script {
                    withEnv(["PATH+MAVEN=${MAVEN_HOME}/bin"]) {
                        sh 'mvn clean install'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    echo 'Test Done'
                }
            }
        }
        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            }
        }
    }
    post {
        always {
            echo 'Pipeline finished.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}